{{- $distro := .distro -}}
{{- $suite := .suite -}}

{{- $vscodium_mirror := or .radxa_mirror "https://download.vscodium.com/" -}}

{{- $architecture := .architecture -}}

architecture: {{ $architecture }}

actions:
  - action: recipe
    description: Add vscodium Repo
    recipe: ../scripts/add_repo.yaml
    variables:
      public_key: https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/raw/master/pub.gpg
      base_url: {{ $vscodium_mirror }}debs
      suite: vscodium

  - action: apt
    description: Install common desktop packages
    packages:
      - accountsservice
      - aha
      - breeze-cursor-theme
      - clinfo
      - codium
      - cups
      - desktop-base
{{ if eq $distro "debian" }}
      - firefox-esr
{{ else if eq $distro "ubuntu" }}
      - firefox
{{ end }}
      - fonts-noto-cjk
      - fprintd
      - fwupd
      - gstreamer1.0-gtk3
      - gstreamer1.0-libav
      - gstreamer1.0-plugins-bad
      - gstreamer1.0-plugins-base
      - gstreamer1.0-plugins-good
      - gstreamer1.0-plugins-rtp
      - gstreamer1.0-plugins-ugly
      - gstreamer1.0-qt5
      - gstreamer1.0-vaapi
      - gvfs
      - gvfs-backends
      - gvfs-fuse
      - mesa-utils
      - mesa-va-drivers
      - plymouth
      - plymouth-theme-breeze
      - plymouth-themes
      - vdpau-driver-all
      - vulkan-tools
      - xdg-desktop-portal
      - xdg-desktop-portal-gtk
      - xdg-user-dirs
      - xdg-user-dirs-gtk
      - xdg-utils
{{ if eq $distro "debian" }}
      - maliit-keyboard
{{ end }}
{{ if ne $suite "focal" }}
      - bup
{{ end }}

{{ if eq $suite "bookworm" }}

  - action: apt
    description: Install Debian 12 packages
    packages:
      - wayland-utils
      - gstreamer1.0-pipewire

{{ else }}

  - action: apt
    description: Install common X.Org packages
    packages:
      - xiccd

{{ end }}
